# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
group :development do
  gem "capistrano", "~> 3.14", require: false
  gem 'capistrano-composer'
  gem 'ed25519', '~> 1.2'
  gem 'bcrypt_pbkdf', '~> 1'
end
